### ISSUE TITLE
[Suggestion] Configuration for send to different Spaces

### ISSUE THREAD

**Issue by luizhm47** [thiagomdiniz/zabbix-google-chat-webhook#1]
A suggestion would be to change the google_endpoint variable to: {ALERT.SENDTO}&threadKey={TRIGGER.ID}

With this, it is possible to send to different Spaces by simply creating a user in Zabbix for each Space and using the Send To field in the user's Media tab.
And with the threadKey, it is possible to keep the alert within the same thread (if the Space is configured to use threads)

**Comment by thiagomdiniz** [comment]
Hi @luizhm47 , thanks for sharing your ideas.

This idea of being able to group related alerts in the same thread is really good.
I tested it here and it worked, but I also had to add the parameter &messageReplyOption=REPLY_MESSAGE_FALLBACK_TO_NEW_THREAD.
I particularly prefer to group messages by {EVENT.ID}, but each one can be configured as you wish.
I will implement this. Thanks for the tip!

About the question of changing the "google_endpoint" parameter, I thought about it when I was implementing it and it really works if you do it like this.
But I asked myself, why didn't Zabbix itself do this for, for example, the [Microsoft Teams webhook](https://git.zabbix.com/projects/ZBX/repos/zabbix/browse/templates/media/msteams)?
![image](https://github.com/thiagomdiniz/zabbix-google-chat-webhook/assets/29825093/56098ffa-c673-4e9f-8de0-92ec32b66283)

And I came to the conclusion that it is a security issue, because if you do that, the Chat webhook URL will be exposed to anyone who has access to the problems in Zabbix.
See the difference:

With the current implementation:
![image](https://github.com/thiagomdiniz/zabbix-google-chat-webhook/assets/29825093/f2744c22-474e-4109-a634-d99f58ea2e92)

Using {ALERT.SENDTO} as you suggested:
![image](https://github.com/thiagomdiniz/zabbix-google-chat-webhook/assets/29825093/ac2ea545-3509-4f38-a335-e2ff3ddb179f)

I don't know your opinion, but by design, I particularly prefer to leave it as it is and clone the webhook in case I need to notify other spaces in the Chat than to expose the URL of the Chat, because with this URL anyone can send messages in the Chat.

**Comment by thiagomdiniz** [comment]
I did some more tests regarding this security issue involving the Google Chat webhook URL, and I came to the conclusion that a Zabbix user can only view these details if he is a "Super Admin" or if he is in the same group as the user who owns the media configured to send the notifications.

Screenshots showing that, for the same Problem, action details are displayed or not according to user permissions:
![image](https://github.com/thiagomdiniz/zabbix-google-chat-webhook/assets/29825093/6c2903ef-1790-4499-b8f3-bc83545be6d7)

![image](https://github.com/thiagomdiniz/zabbix-google-chat-webhook/assets/29825093/b8ad3c0e-6d6b-4169-8951-83b8762c2f55)


So I created a branch to add the details on how to send notifications to multiple spaces just by creating users and using the {ALERT.SENDTO} macro.
Thanks!
